version: "{build}"
branches:
  only:
  - master
  - appveyor
  - hunter
configuration:
  - Release
environment:
  HUNTER_CACHE_TOKEN:
    secure: agYfiC1OKfHnGOJQolOBorIRovVTgDW3TJ8JOb2+0XZiAnNwbrtPegxaaFM8/VWu
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
#      CONFIGURATION: Debug

#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      GENERATOR: "Visual Studio 15 2017"
#
#    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#      GENERATOR: "Visual Studio 14 2015 Win64"

install:
  # Python 3
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  - pip install requests wheel

before_build: |
  cmake -S . -B build -G "%GENERATOR%" .. -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% -DETHASH_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=dist

build_script: |
  cmake --build build --config %CONFIGURATION% --target install
  python setup.py bdist_wheel

test_script: |
  python setup.py test

artifacts:
  - path: dist
    name: dist
